### ISSUE TITLE
Requesting for Registering of Cards In-App Provisioning

### ISSUE THREAD

**Issue by jagan27101986** [samkelleher/cordova-plugin-applepay#12]
Hi,
I am having a requirement where i need to check whether the devices support Apple Pay and then we need to register the card in the mobile application (In-App Provisioning) . I see that the plugin supports only making Payments and transactions. Is there a way to create a Cordova plugin for registering of cards which will be useful for all the users.

**Comment by jagan27101986** [comment]
It will be good if you can support from Cordova 3.0 version

**Comment by samkelleher** [comment]
Hello.

Cordova 3.0 is over 4 years old and is not supported. I'll be surprised if apps that old even still work on iOS.

The app cannot register a card, but the API does have a `openPaymentSetup` option - but all this does is open the Wallet app on the users phone. They leave your app. Apple Pay doesn't support adding cards during the payment flow while your app is open.

If the device supports apple pay but has no cards setup, you can prompt the user to open the wallet app themselves, or simply not show an Apple Pay option.

(When we tested this internally, we found nobody started the Apple Pay setup process, or those that did never returned).  I.e. we had better conversions showing regular in app card payment options than forcing someone down a route to setup Apple Pay, especially since not everyone has an Apple Pay compatible card.

I'll close the issue but feel free to comment.

**Comment by jagan27101986** [comment]
Hi Sam,

Thanks for the comments. However i will check if there is any.
