### ISSUE TITLE
Plugin doesn't recognized cards in ApplePay Wallet

### ISSUE THREAD

**Issue by nexus1892** [samkelleher/cordova-plugin-applepay#14]
Hi, I have added a credit card to my applepay wallet, however when I use the plugin to verify a purchase can be made it returns the following, "This device can make payments but has no supported cards".  I am on iOS 10.3.2 and Cordova 7.0.1.  Any help tracking down the issue would be very helpful!  Thanks.

**Comment by samkelleher** [comment]
Hello @nexus1892  - the plugin is just wrapping the call to `canMakePayments()` which is documented here > https://developer.apple.com/documentation/passkit/pkpaymentauthorizationviewcontroller/1616192-canmakepayments

I can't comment on your specific setup since I don't know if you've setup your Apple Pay correctly, the card is valid and its limitations, location and if you've setup your app correctly.

I the top of the `CDVApplePay.m` file, there are some hard coded requirments:

```
- (void)pluginInitialize
{

    // Set these to the payment cards accepted.
    // They will nearly always be the same.
    supportedPaymentNetworks = @[PKPaymentNetworkVisa, PKPaymentNetworkMasterCard, PKPaymentNetworkAmex];

    // Set the capabilities that your merchant supports
    // Adyen for example, only supports the 3DS one.
    merchantCapabilities = PKMerchantCapability3DS;// PKMerchantCapabilityEMV;


}
```

These are the most common settings and I've never enounctered a user with settings different this but maybe you're the first! Basically requries 3DS merchant with Visa, Amex, or MasterCard.

Check your card meets these requirements and if Apple Pay works in some other apps.

Thanks for stopping by, make another comment if you need more info.

**Comment by nexus1892** [comment]
Thank you for the reply.  Unfortunately the problem persists.  I added a second credit card to my wallet and confirmed that both cards are setup for ApplePay(mastercard and visa).  I have not changed the hardcoded settings above.  The only thing I have done in my code is make a call to ApplePay.canMakePayments with the same code provided in the tutorial.  I added this code to the onDeviceReady after Cordova is initialized.  Please advise for anything else I can try.

**Comment by nexus1892** [comment]
This was happening because Apple Pay wasn't enabled under Capabilities in the target settings in Xcode.
