### ISSUE TITLE
Linking with Authorize.net

### ISSUE THREAD

**Issue by earth** [samkelleher/cordova-plugin-applepay#15]
Please let me know how can i use Authorize.net for Apple Pay using this plugin - cordova-plugin-applepay

**Comment by samkelleher** [comment]
You can use whichever payment processor you want @earth  - this plugin just exposes the payment token to your application, how you handle it is totally in your control.

You would need to consult Authorize.net's documentation, and if they provide a cordova plugin or similiar and support Apple Pay tokens, then you can integrate their token.

Most payment providers have some sort of SDK you can consume that will have a method that will accept an Apple Pay token for payment processing.

There are people who have forked this plugin and done the same thing using Stripe, so that would be a good reference material to look at.
