### ISSUE TITLE
makePaymentRequest error

### ISSUE THREAD

**Issue by hsmith825** [samkelleher/cordova-plugin-applepay#4]
using cordova 6.0.0 and Xcode 7.3.1

My flow is as follows;

ApplePay.canMakePayments() - Apple Pay is enabled and a supported card is setup

var worder = "{items: [{label: '3 x Basket Items',amount: .25}],merchantIdentifier: '" +apple_merchantid +"',currencyCode: 'USD',countryCode: 'US',billingAddressRequirement: 'none',shippingAddressRequirement: 'none',shippingType: 'service'}";
ApplePay.makePaymentRequest( worder)
   .then(wsuccess(token))
    .catch(wfail(e));
result is:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x15eb84ef0'

Any ideas are welcomed!!!
thanks!
Howard

**Comment by samkelleher** [comment]
Hi @hsmith825 .

Can you provide a complete stack trace of your error? The message isn't enough to go on as could be caused by anything.

I do note that your 'worder' is a string and not a JS object.

Also your `then` and `catch` functions can't have other functions passed into them, your essentially calling your success and failure methods at the same time as the makePaymentRequest.

Examine the example included in the plugin Readme.

* Don't self-call your promise resolvers
* Provide the worder as an object, not a string.

Hope this helps. If you find this doesn't, please re-open the issue.
