### ISSUE TITLE
Token not valid for Stripe

### ISSUE THREAD

**Issue by hsmith825** [samkelleher/cordova-plugin-applepay#7]
Hi Sam,

This is similar to comments I placed under a closed issue.

According to Stripe. You left the final step out of your plugin. That is the step that converts the Apple Pay token into a Stripe token. All the tools that interface to Stripe provide this step. Below is the code that will do this:
// ViewController.m

(void)handlePaymentAuthorizationWithPayment:(PKPayment )payment completion:(void (^)(PKPaymentAuthorizationStatus))completion { [[STPAPIClient sharedClient] createTokenWithPayment:payment completion:^(STPToken *token, NSError *error) { if (error) { completion(PKPaymentAuthorizationStatusFailure); return; } / We'll implement this below in "Sending the token to your server". Notice that we're passing the completion block through. See the above comment in didAuthorizePayment to learn why. */ [self createBackendChargeWithToken:token completion:completion]; }]; }
I don't know how to add this to your plugin. Can you help? We have spend days trying to solve this ourselves.

Your help is appreciated.
Thanks!!!

**Comment by samkelleher** [comment]
Hello!

If you want to use a native SDK, like the one stripe provide, you'll have to fork and adapt this plugin.  Actually I originally forked the plugin and it had a Stripe SDK embedded, but the original found was very unstable and 'early alpha' - didn't have the completion handling or anything.  This is why I wrote this plugin as I needed full production safe plugin.

Basically, you need to intercept the Apple PKPayment - the object that Apple Pay generates - and give it to stripe in native code, rather than in JavaScript (via cordova) which this plugin is for.

Ideally you'd find a Cordova Stripe plugin - and you can do it all separately within your JavaScript application without rolling your own customisations in this plugin.

https://github.com/samkelleher/cordova-plugin-applepay/blob/master/src/ios/CDVApplePay.m#L589

This line is where the PKPayment is handled, and this is what the Stripe SDK is referring to. Here you can write your own code from the Stripe sample.

Drop me a message/comment if you need any pointers.

Thanks,

Sam

**Comment by hsmith825** [comment]
Thanks Sam,

 

When I get a chance I will take a look.

 

Howard
